# Aritmética y variables

En este archivo se encuentran los comandos básicos de Python. Los temas que se verán en este submódulo son:

    1. Definición e impresion de variables
    2. Operaciones básicas
    3. List, Tupples, Sets y Diccionaries

## Tarea 

Hacer los ejercicios de la página [link](https://www.w3schools.com/python/python_exercises.asp) y tomar una captura de pantalla de que todos fueron hechos con el nombre del alumno en el URL. 

**OBS:** Puede sonar a que son muchos, pero la mayoría toma menos de 5 segundos hacerlos. 

## Páginas útiles

Algunas páginas relacionadas a estos temas son:

   1. Comparativo entre List, Tupples, Sets y Diccionaries [link](https://www.geeksforgeeks.org/differences-and-applications-of-list-tuple-set-and-dictionary-in-python/).

### COMENTARIOS
Se explica cómo poner comentarios en el código. Comentarios de un reglón o de más de un renglón.

In [80]:
'''Para poner un comentario largo 
se utilizan 3 comillas simples'''

""" ó 3 comilas 
dobles. """

#Para comentarios de un renglón se usa el símbolo de número o gato o hashtag

' ó 3 comilas \ndobles. '

### DEFINICIÓN DE VARIABLES
Se definen variables tipo caracter y numérico.

In [91]:
color = "azul"
mascota = 'Sandy'
risa = 'ja'
a = 1
b = 2

### FUNCIÓN print()
Sirve para imprimir texto en el programa.

In [92]:
#Variables tipo string:
print("Mi color favorito es: " + color)

#Valor de variables tipo numéricas.
print(a)
print(a+1)
print(a+b)

#En caso de querer imprimir un texto con un salto de línea se utiliza el comando \n
print("Mi color favorito es: " + color + "\nMi mascota se llama: " + mascota)

#Para concatenar strings con variables numéricas se utilizan comas:
print("El valor de a es: ",a)
print("El valor de a es: "+ str(a))

Mi color favorito es: azul
1
2
3
Mi color favorito es: azul
Mi mascota se llama: Sandy
El valor de a es:  1
El valor de a es: 1


### OPERADOR *=
Define nuevamente una variable multiplicada por el número de veces que se indica.

In [93]:
print(b)
b *= 5
print(b)

print(risa)
risa *= 3
print(risa)

2
10
ja
jajaja


### Función round()
Redondea un número al entero más cercano. Se le puede indicar el número de decimales al que se desea redondear.

In [87]:
round(3.141592)

3

In [86]:
round(3.141592,2)

3.14

### OPERACIONES BÁSICAS
Se importa la librería math. Las funciones se cargan poniendo al inicio math.

In [52]:
import math

a = 1
b = 2
x = math.pi
n = 10

In [55]:
#Suma
a + b

3

In [53]:
3 + 6

9

In [54]:
7 + b

9

In [58]:
#Resta
a-b

-1

In [57]:
b-a

1

In [61]:
#Multiplicación
a*b

2

In [62]:
#División
a/b

0.5

In [63]:
b/a

2.0

In [64]:
#Función piso
math.floor(x)

3


In [65]:
#Función techo
math.ceil(x)

4


In [66]:
#log = logaritmo natural (base e)
math.log(x)

1.1447298858494002

In [67]:
math.log(math.exp(1))

1.0

In [68]:
#logaritmo base n
math.log(x,n)

0.4971498726941338

In [69]:
math.log(10,n)

1.0

In [70]:
#Número e
math.exp(1) #e^1

2.718281828459045

In [71]:
math.exp(x) #e^x

23.140692632779267

In [72]:
#Potencias
2**3

8

In [73]:
pow(2, 3)

8

In [74]:
#Raíz Cuadrada
math.sqrt(b)

1.4142135623730951

In [75]:
#Funciones Trigonométricas
math.sin(math.pi/2)

1.0

In [76]:
math.cos(2*math.pi)

1.0

In [79]:
math.tan(math.pi)

-1.2246467991473532e-16

In [84]:
math.asin(1) #arcsin(x)

1.5707963267948966

In [81]:
math.acos(0) #arccos(x)

1.5707963267948966

In [82]:
math.atan(1) #arctan(x)

0.7853981633974483

In [92]:
#Factorial: n! = n*(n-1)*(n-2)*...*2*1
math.factorial(5)

120

### NÚMEROS ALEATORIOS
Se importa la librería random. Se generan números aleatorios enteros y con decimales. Se pueden hacer elecciones aleatorias de conjuntos de números o de variables tipo caracter.

In [101]:
import random

'''La función random.randint(a, b) devuelve un número aleatorio
entero elegido de [a,b].'''
random.randint(0,100)

10

In [112]:
'''La función random.randrange(a, b, salto) genera números enteros
aleatorios en [a,b] con un "salto". En el siguiente ejemplo se 
toman los valores del conjunto {0,2,4,6,8,10}.'''
random.randrange(0, 10, 2)

6

In [122]:
'''La función random.random() devuelve un número aleatorio
tomado del intervalo [0, 1).'''
random.random()

0.08959651494852838

In [130]:
'''La función random.uniform(a,b) devuelve un número aleatorio
tomado del intervalo [a, b]'''
random.uniform(10,20)

15.587326021560143

In [142]:
'''La función random.choice(conj) devuelve un elemento aleatorio de
un conjunto de valores. Pueden ser variables tipo caracter o 
variables numéricas.'''
frutas = ['peras', 'manzanas', 'plátanos', 'ciruelas']
random.choice(frutas)

'peras'

In [151]:
num = [1,2,3,4,5,6,7,8,9,10]
random.choice(num)

4

In [156]:
'''La función random.sample(conj,n) devuelve "n" elementos
aleatorios de un conjunto de valores. Pueden ser variables tipo
caracter o variables numéricas.'''
random.sample(frutas,2)

['peras', 'ciruelas']

In [163]:
random.sample(num,2)

[10, 4]

### Booleanos
Nos indican cuando una condición es verdadera o falsa.

In [164]:
a<b

True

In [165]:
b<a

False

In [166]:
a==b #Preguntamos si los números son iguales

False

In [167]:
a != b #Preguntamos si los números son diferentes

True

### ARRAY (ARREGLOS)
Los arreglos son vectores. La posición de los elementos se empieza a contar en 0.

In [97]:
import numpy as np
#El comando "as np" permite llamar a las funciones con "np."

v=np.array([1,2,3,4,5])
print(v)

w=np.array([5,5,5])
print(w)

vec = [1,2,3,4,5,6,7]
print(vec)

print("La longitud de vec es:",len(vec))

[1 2 3 4 5]
[5 5 5]
[1, 2, 3, 4, 5, 6, 7]
La longitud de vec es: 7


In [37]:
v+v #Suma de vectores

array([ 2,  4,  6,  8, 10])

In [94]:
b*v #Vector por escalar

array([10, 20, 30, 40, 50])

In [39]:
u = np.arange(0,20,2) #Toma los valores en [0,20)
u

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [180]:
u[0] #Se muestra el primer elemento del vector "u".

0

In [181]:
u[1] #Se muestra el segundo elemento del vector "u".

2

In [88]:
u[1] = 5.5 #Se cambia la segunda entrada de "u".
print(u)

[ 0  5  4  6  8 10 12 14 16 18]


In [183]:
#Se muestran los elementos en las posiciones 2,3,4 del vector "u".
u[2:5]

array([4, 6, 8])

In [184]:
#Se muestran desde el primer elemento hasta la posición 4
u[:5]

array([0, 2, 4, 6, 8])

In [185]:
#Se muestran desde la posición 2 hasta el último elemento
u[2:]

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [96]:
#Se eliminan los elementos en los índices 5,6 y 7.
del vec[5:8]
print(vec)

[1, 2, 3, 4, 5]


### MATRICES
Se definen como una lista de listas o en base a los arreglos.

In [99]:
mat = np.arange(1, 10).reshape(3,3)
print(mat,"\n")
print("La dimensión de mat es:",mat.shape)

print("La matriz mat tiene:",mat.shape[0]," renglones y ",mat.shape[1]," columnas.")

mat_2 = np.array([[9,8,7],[6,5,4],[3,2,1]])
print(mat_2,"\n")

#Lista de listas
mat_3=  [[8, 14, -6],[12, 7, 4],[-11, 3, 21]]
print(mat_3)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

La dimensión de mat es: (3, 3)
La matriz mat tiene: 3  renglones y  3  columnas.
[[9 8 7]
 [6 5 4]
 [3 2 1]] 

[[8, 14, -6], [12, 7, 4], [-11, 3, 21]]


In [24]:
# Cuidado al definir los valores de las matrices
mat_error = np.arange(1, 9).reshape(3,3)
mat_error

In [25]:
#Se muestra el primer renglón de cada matriz
mat[0]

array([1, 2, 3])

In [26]:
mat_2[0]

array([9, 8, 7])

In [27]:
mat_3[0]

[8, 14, -6]

In [30]:
np.empty((2, 3))# Matriz vacía, con valores residuales de la memoria

array([[0., 0., 0.],
       [0., 0., 0.]])

In [191]:
np.zeros((3, 3)) # Matriz de ceros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [192]:
np.ones((3, 2)) # Matriz de unos

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### OPERACIONES CON MATRICES
Se muestran operaciones entrada por entrada y con las matrices completas.

In [29]:
#Suma
mat + mat_2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [31]:
mat + mat_3

array([[ 9, 16, -3],
       [16, 12, 10],
       [-4, 11, 30]])

In [28]:
mat - mat_2

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

In [32]:
#Multiplicación de matrices
mat.dot(mat_2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [42]:
#Multiplicación de vector por matriz
w.dot(mat)

array([60, 75, 90])

In [ ]:
#Divide entrada por entrada
np.divide(mat,mat_2)

In [43]:
#Transpuesta de una matriz
mat.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [78]:
mat.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [54]:
#Muestra el primer renglón
mat[:1,]

array([[1, 2, 3]])

In [71]:
#Muestra la primer columna
mat[:,0]

array([1, 4, 7])

In [65]:
#Muestra los primeros 2 renglones y las primeras 2 columnas
mat[:2,:2]

array([[1, 2],
       [4, 5]])

In [72]:
#Divide entrada por entrada
np.divide(mat,mat_2)

array([[0.11111111, 0.25      , 0.42857143],
       [0.66666667, 1.        , 1.5       ],
       [2.33333333, 4.        , 9.        ]])

In [73]:
#Multiplica entrada por entrada
np.multiply(mat,mat_2)

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [74]:
#Raíz cuadrada entrada por entrada
np.sqrt(mat)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [75]:
#Suma de elementos
np.sum(mat)

45

In [76]:
#Suma por columnas
np.sum(mat,axis=0)

array([12, 15, 18])

In [77]:
#Suma por renglones
np.sum(mat,axis=1)

array([ 6, 15, 24])