# Aritmética y variables

En este archivo se encuentran los comandos básicos de Python. Los temas que se verán en este submódulo son:

    1. Definición e impresión de variables
    2. Operaciones básicas
    3. List, Tuples, Sets y Dictionaries

## Tarea 

Hacer los ejercicios de la página [link](https://www.w3schools.com/python/python_exercises.asp) y tomar una captura de pantalla de que todos fueron hechos con el nombre del alumno en el URL. 

**OBS:** Puede sonar a que son muchos, pero la mayoría toma menos de 5 segundos hacerlos. 

## Páginas útiles

Algunas páginas relacionadas a estos temas son:

   1. Comparativo entre List, Tuples, Sets y Dictionaries [link](https://www.geeksforgeeks.org/differences-and-applications-of-list-tuple-set-and-dictionary-in-python/).

### COMENTARIOS
Se explica cómo poner comentarios en el código. Comentarios de un reglón o de más de un renglón.

In [ ]:
'''Para poner un comentario largo 
se utilizan 3 comillas simples'''

""" ó 3 comilas 
dobles. """

#Para comentarios de un renglón se usa el símbolo de número o gato o hashtag

### DEFINICIÓN DE VARIABLES
Se definen variables tipo caracter y numérico.

In [5]:
color = "azul"
mascota = 'Sandy'
risa = 'ja'
a = 1
b = 2

### FUNCIÓN _print()_
Sirve para imprimir texto en el programa.

In [3]:
#Variables tipo string:
print("Mi color favorito es: " + color)

#Valor de variables tipo numéricas.
print(a)
print(a+1)
print(a+b)

#En caso de querer imprimir un texto con un salto de línea se utiliza el comando \n
print("Mi color favorito es: " + color + "\nMi mascota se llama: " + mascota)

#Para concatenar strings con variables numéricas se utilizan comas:
print("El valor de a es: ",a)
print("El valor de a es: "+ str(a))

Mi color favorito es: azul
1
2
3
Mi color favorito es: azul
Mi mascota se llama: Sandy
El valor de a es:  1
El valor de a es: 1


### OPERADOR *=
Define nuevamente una variable multiplicada por el número de veces que se indica.

In [4]:
print(b)
b *= 5
print(b)

print(risa)
risa *= 3
print(risa)

2
10
ja
jajaja


### FUNCIÓN _round()_
Redondea un número al entero más cercano. Se le puede indicar el número de decimales al que se desea redondear.

In [5]:
round(3.141592)

3

In [6]:
round(3.141592,2)

3.14

### OPERACIONES BÁSICAS
Se importa la librería math. Las funciones se cargan poniendo al inicio math.

In [6]:
import math

a = 1
b = 2
x = math.pi
n = 10

In [8]:
#Suma
a + b

3

In [9]:
3 + 6

9

In [10]:
7 + b

9

In [11]:
#Resta
a-b

-1

In [12]:
b-a

1

In [13]:
#Multiplicación
a*b

2

In [14]:
#División
a/b

0.5

In [15]:
b/a

2.0

In [16]:
#Función piso
math.floor(x)

3

In [17]:
#Función techo
math.ceil(x)

4

In [18]:
#log = logaritmo natural (base e)
math.log(x)

1.1447298858494002

In [19]:
math.log(math.exp(1))

1.0

In [20]:
#logaritmo base n
math.log(x,n)

0.4971498726941338

In [21]:
math.log(10,n)

1.0

In [22]:
#Número e
math.exp(1) #e^1

2.718281828459045

In [23]:
math.exp(x) #e^x

23.140692632779267

In [24]:
#Potencias
2**3

8

In [25]:
pow(2, 3)

8

In [26]:
#Raíz Cuadrada
math.sqrt(b)

1.4142135623730951

In [27]:
#Funciones Trigonométricas
math.sin(math.pi/2)

1.0

In [28]:
math.cos(2*math.pi)

1.0

In [29]:
math.tan(math.pi)

-1.2246467991473532e-16

In [30]:
math.asin(1) #arcsin(x)

1.5707963267948966

In [31]:
math.acos(0) #arccos(x)

1.5707963267948966

In [32]:
math.atan(1) #arctan(x)

0.7853981633974483

In [33]:
#Factorial: n! = n*(n-1)*(n-2)*...*2*1
math.factorial(5)

120

### NÚMEROS ALEATORIOS
Se importa la librería random. Se generan números aleatorios enteros y con decimales. Se pueden hacer elecciones aleatorias de conjuntos de números o de variables tipo caracter.

In [40]:
import random

'''La función random.randint(a, b) devuelve un número aleatorio
entero elegido de [a,b].'''
random.randint(0,100)

24

In [44]:
'''La función random.randrange(a, b, salto) genera números enteros
aleatorios en [a,b] con un "salto". En el siguiente ejemplo se 
toman los valores del conjunto {0,2,4,6,8,10}.'''
random.randrange(0, 10, 2)

8

In [48]:
'''La función random.random() devuelve un número aleatorio
tomado del intervalo [0, 1).'''
random.random()

0.4539744561954332

In [52]:
'''La función random.uniform(a,b) devuelve un número aleatorio
tomado del intervalo [a, b]'''
random.uniform(10,20)

18.754719331916437

In [57]:
'''La función random.choice(conj) devuelve un elemento aleatorio de
un conjunto de valores. Pueden ser variables tipo caracter o 
variables numéricas.'''
frutas = ['peras', 'manzanas', 'plátanos', 'ciruelas']
random.choice(frutas)

'ciruelas'

In [61]:
num = [1,2,3,4,5,6,7,8,9,10]
random.choice(num)

5

In [66]:
'''La función random.sample(conj,n) devuelve "n" elementos
aleatorios de un conjunto de valores. Pueden ser variables tipo
caracter o variables numéricas.'''
random.sample(frutas,2)

['peras', 'manzanas']

In [69]:
random.sample(num,2)

[9, 10]

### BOOLEANOS
Nos indican cuando una condición es verdadera o falsa.

In [71]:
print(a)
print(b)
a<b

1
2


True

In [72]:
b<a

False

In [73]:
a==b #Preguntamos si los números son iguales

False

In [74]:
a != b #Preguntamos si los números son diferentes

True

### ARRAY (ARREGLOS)
Los arreglos son vectores. La posición de los elementos se empieza a contar en 0.

In [2]:
import numpy as np
#El comando "as np" permite llamar a las funciones con "np."

v=np.array([1,2,3,4,5])
print(v)

w=np.array([5,5,5])
print(w)

vec = [1,2,3,4,5,6,7]
print(vec)

print("La longitud de vec es:",len(vec))

[1 2 3 4 5]
[5 5 5]
[1, 2, 3, 4, 5, 6, 7]
La longitud de vec es: 7


In [3]:
v+v #Suma de vectores

array([ 2,  4,  6,  8, 10])

In [8]:
print(b)
b*v #Vector por escalar

2


array([ 2,  4,  6,  8, 10])

In [9]:
u = np.arange(0,21,2) #Toma los valores en [0,21)
print(u)
u.dtype #dtype = data type // indica el tipo de dato, en este caso u es de tipo 'int32'

[ 0  2  4  6  8 10 12 14 16 18 20]


dtype('int32')

In [10]:
u[1] = 5.5 #Se cambia la segunda entrada de "u".
print(u)
u.dtype

[ 0  5  4  6  8 10 12 14 16 18 20]


dtype('int32')

In [11]:
#En caso de que querramos que los valores de 'u' sean de tipo flotante.
u = np.arange(0,20.1,2) #Toma los valores en [0,20.1)
u = np.arange(0,21,2,dtype = float) #Toma los valores en [0,21)
print(u)
u.dtype

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


dtype('float64')

In [81]:
u[0] #Se muestra el primer elemento del vector "u".

0

In [82]:
u[1] #Se muestra el segundo elemento del vector "u".

2

In [95]:
u[1] = 5.5 #Se cambia la segunda entrada de "u".
print(u)
u.dtype

[ 0.   5.5  4.   6.   8.  10.  12.  14.  16.  18.  20. ]


dtype('float64')

In [85]:
#Se muestran los elementos en las posiciones 2,3,4 del vector "u".
u[2:6]

array([ 4,  6,  8, 10])

In [86]:
#Se muestran desde el primer elemento hasta la posición 4
u[:5]

array([0, 5, 4, 6, 8])

In [87]:
#Se muestran desde la posición 2 hasta el último elemento
u[2:]

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20])

In [88]:
#Se eliminan los elementos en los índices 5,6 y 7.
print(vec)
del vec[5:8]
print(vec)

[1, 2, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 5]


### LIST
Sirve para guardar múltiples elementos en una misma variable.

Se pueden guardar valores de tipo caracter, numérico, booleano o combinados.

Se definen con corchetes o con el comando "list()".

Se pueden modificar sus elementos.

In [82]:
#Lista de caracteres.
lista_1 = ["abc", "def", "ghi"]
print(lista_1)

#Lista de valores numéricos.
lista_2 = [1, 2, 3, 4, 5, 5, 1, 2, 3] #Permite valores repetidos
print(lista_2)

#Lista de booleanos.
lista_3 = [True,False,1<2,1>2]
print(lista_3)

#Lista de valores combinados.
lista_4 = ["abc", 123, True, 2<0]
print(lista_4)

#Definición con el comando "list()"
lista_5 = list(("lista", "con", "caracteres")) #Se define con doble paréntesis.
print(lista_5)

#Lista de listas
lista_6 = [lista_1,lista_2,lista_3]
print(lista_6)

#Lista vacía
lista_v = []
print(lista_v)

#Lista definida con operaciones
lista_op = [2 ** x for x in range(10)] #2^n, con n = 0,1, ... ,9
print(lista_op)

['abc', 'def', 'ghi']
[1, 2, 3, 4, 5, 5, 1, 2, 3]
[True, False, True, False]
['abc', 123, True, False]
['lista', 'con', 'caracteres']
[['abc', 'def', 'ghi'], [1, 2, 3, 4, 5, 5, 1, 2, 3], [True, False, True, False]]
[]
[1, 2, 4, 8, 16, 32, 64, 128, 256, 512]


In [15]:
#Para acceder a los elementos de una lista se utilizan los corchetes.

print(lista_1[1]) #Se muestra el segundo elemento.

print(lista_6[0][1]) #De la primer lista, se muestra el segundo elemento.


def
def


### OPERACIONES CON LISTAS

- Conocer la longitud de una lista

- Cambiar elementos

- Eliminar elementos

- Agregar nuevos elementos

- Ordenar elementos

- Otras

In [18]:
# Longitud de una lista
len(lista_3)

4

In [19]:
len(lista_6)

3

In [20]:
len(lista_6[1])

6

In [17]:
# Cambiar elementos
print(lista_2[5])
lista_2[5] = 6.2
print(lista_2)

5
[1, 2, 3, 4, 5, 6.2]


In [58]:
# Eliminar elementos
print(lista_5)
del lista_5[1] #Se elimina el elemento en el índice 1
print(lista_5)

lista_5.remove('lista') #Se elimina el elemento "lista"
print(lista_5)

print(lista_2)
print(lista_2.pop()) #Se muestra y se elimina el último elemento de la lista
print(lista_2)

print(lista_2.pop(1)) #Se muestra y se elimina el elemento en el índice 1
print(lista_2)

lista_2.clear() #Se vacía la lista
print(lista_2)

['lista', 'con', 'caracteres']
['lista', 'caracteres']
['caracteres']
[1, 2, 3, 4, 5, 5]
5
[1, 2, 3, 4, 5]
2
[1, 3, 4, 5]
[]


In [41]:
# Agregar un elemento
print(lista_4)
lista_4.append(5)
print(lista_4)

# Agregar varios elementos
lista_4.extend([10,math.pi,'jkl'])#Se agrega una lista de elementos
print(lista_4)

#Insertar un elemento
lista_4.insert(1,3) # Se agrega el 3 en la posición con índice 1
print(lista_4)

['abc', 123, True, False]
['abc', 123, True, False, 5]
['abc', 123, True, False, 5, 10, 3.141592653589793, 'jkl']
['abc', 3, 123, True, False, 5, 10, 3.141592653589793, 'jkl']


In [33]:
# Concatenar listas
print(lista_1 + lista_2)

['abc', 'def', 'ghi', 1, 2, 3, 4, 5, 5]


In [35]:
# Repetir listas
print(lista_5 * 3)

['lista', 'con', 'caracteres', 'lista', 'con', 'caracteres', 'lista', 'con', 'caracteres']


In [67]:
# Índice de un elemento: La función regresa el índice del primer elemento que coincida.
lista_4.index(123)

1

In [71]:
# Contar elementos
print(lista_2)
lista_2.count(5) #Regresa el número de veces que se encuentra el elemento (5) en la lista

[1, 2, 3, 4, 5, 5, 1, 2, 3]


2

In [79]:
# Ordenar los elementos
print(lista_2)
lista_2.sort() # Ordena de menor a mayor
print(lista_2)

print(lista_5)
lista_5.sort() # Ordena alfabéticamente
print(lista_5)

[1, 1, 2, 2, 3, 3, 4, 5, 5]
[1, 1, 2, 2, 3, 3, 4, 5, 5]
['lista', 'con', 'caracteres']
['caracteres', 'con', 'lista']


In [80]:
# Invierte el orden de los elementos
print(lista_2)
lista_2.reverse()
print(lista_2)

[1, 1, 2, 2, 3, 3, 4, 5, 5]
[5, 5, 4, 3, 3, 2, 2, 1, 1]


In [81]:
# Regresa una copia de la lista
lista_2.copy()

[5, 5, 4, 3, 3, 2, 2, 1, 1]


[5, 5, 4, 3, 3, 2, 2, 1, 1]

In [84]:
# Buscar elemento en la lista
10 in lista_2

False

In [85]:
10 not in lista_2

True

### MATRICES
Se definen como una lista de listas o en base a los arreglos.

In [ ]:
mat = np.arange(1, 10).reshape(3,3)
print(mat,"\n")
print("La dimensión de mat es:",mat.shape)

print("La matriz mat tiene:",mat.shape[0]," renglones y ",mat.shape[1]," columnas.")

mat_2 = np.array([[9,8,7],[6,5,4],[3,2,1]])
print(mat_2,"\n")

#Lista de listas
mat_3=  [[8, 14, -6],[12, 7, 4],[-11, 3, 21]]
print(mat_3)

In [12]:
# Cuidado al definir los valores de las matrices
mat_error = np.arange(1, 9).reshape(3,3)
mat_error

ValueError: cannot reshape array of size 8 into shape (3,3)

In [ ]:
#Se muestra el primer renglón de cada matriz
mat[0]

In [ ]:
mat_2[0]

In [ ]:
mat_3[0]

In [ ]:
np.empty((2, 3))# Matriz vacía, con valores residuales de la memoria

In [ ]:
np.zeros((3, 3)) # Matriz de ceros

In [ ]:
np.ones((3, 2)) # Matriz de unos

### OPERACIONES CON MATRICES
Se muestran operaciones entrada por entrada y con las matrices completas.

In [ ]:
#Suma
mat + mat_2

In [ ]:
mat + mat_3

In [ ]:
mat - mat_2

In [ ]:
#Multiplicación de matrices
mat.dot(mat_2)

In [ ]:
#Multiplicación de vector por matriz
w.dot(mat)

In [ ]:
#Divide entrada por entrada
np.divide(mat,mat_2)

In [ ]:
#Transpuesta de una matriz
mat.transpose()

In [ ]:
mat.T

In [ ]:
#Muestra el primer renglón
mat[:1,]

In [ ]:
#Muestra la primer columna
mat[:,0]

In [ ]:
#Muestra los primeros 2 renglones y las primeras 2 columnas
mat[:2,:2]

In [ ]:
#Divide entrada por entrada
np.divide(mat,mat_2)

In [ ]:
#Multiplica entrada por entrada
np.multiply(mat,mat_2)

In [ ]:
#Raíz cuadrada entrada por entrada
np.sqrt(mat)

In [ ]:
#Suma de elementos
np.sum(mat)

In [ ]:
#Suma por columnas
np.sum(mat,axis=0)

In [ ]:
#Suma por renglones
np.sum(mat,axis=1)

### TUPLE

Tiene las mismas características que una lista, pero **no** se pueden modificar sus elementos. Ésto permite que las iteraciones hechas con un _tuple_ sean más rápidas que con una lista.

Se definen con paréntesis.

Usualmente se usa con datos de diferente tipo.
<!---
Las listas se utilizan generalmente con el mismo tipo de datos
-->

In [145]:
#Tuple de caracteres.
tuple1 = ("abc", "def", "ghi")
print(tuple1)

#Tuple de valores numéricos.
tuple2 = (1, 2, 3, 4, 5, 5, 1, 2, 3) #Permite valores repetidos
print(tuple2)

#Tuple de booleanos.
tuple3 = (True,False,1<2,1>2)
print(tuple3)

#Tuple de valores combinados.
tuple4 = ("abc", 123, True, 2<0)
print(tuple4)

#Definición con el comando "tuple()"
tuple5 = tuple(("tuple", "con", "caracteres")) #Se define con doble paréntesis.
print(tuple5)

#Tuple de listas
tuple6 = (456,lista_1,lista_2,lista_3)
print(tuple6)

#Tuple vacío
tuple_v = ()
print(tuple_v)

('abc', 'def', 'ghi')
(1, 2, 3, 4, 5, 5, 1, 2, 3)
(True, False, True, False)
('abc', 123, True, False)
('tuple', 'con', 'caracteres')
(456, ['abc', 'def', 'ghi'], [1, 2, 3, 4, 5, 6, 7, 8, 9, 3], [True, False, True, False])
()


In [92]:
# Tuple packing: Se define un tuple sin paréntesis
tuple_p = 1,4,7 #En caso de que el tuple tenga un solo elemento se debe agregar una coma al final.
print(tuple_p)

# Tuple unpacking: Se definen varias variables al mismo tiempo
x,y,z = tuple_p
print(x)
print(y)
print(z)

(1, 4, 7)
1
4
7


In [94]:
# Si el tuple tiene como elemento una lista, esa lista se puede modificar
print(tuple6)
tuple6[2][5:8] = 6,7,8,9 #Se insertan valores a la lista contenida en el tuple
print(tuple6)

(456, ['abc', 'def', 'ghi'], [1, 2, 3, 4, 5, 5, 1, 2, 3], [True, False, True, False])
(456, ['abc', 'def', 'ghi'], [1, 2, 3, 4, 5, 6, 7, 8, 9, 3], [True, False, True, False])


In [95]:
# Concatenar tuples
tuple1 + tuple2

('abc', 'def', 'ghi', 1, 2, 3, 4, 5, 5, 1, 2, 3)

In [97]:
# Repetir tuple
tuple4*2

('abc', 123, True, False, 'abc', 123, True, False)

In [98]:
# Borrar tuple
print(tuple3)
del tuple3
print(tuple3) #Manda error porque se eliminó la variable

(True, False, True, False)


NameError: name 'tuple3' is not defined

In [101]:
#Contar elementos
print(tuple2)
tuple2.count(3)

(1, 2, 3, 4, 5, 5, 1, 2, 3)


2

In [102]:
#Índice de elemento
print(tuple2)
tuple2.index(3)

(1, 2, 3, 4, 5, 5, 1, 2, 3)


2

In [105]:
#Pertenencia de un elemento en un tuple
print(5 in tuple2)

print(5 not in tuple2)

True
False


### SET (CONJUNTOS)

Es una colección de elementos únicos. Los elementos no se pueden modificar pero se pueden agregar o quitar elementos de _set_.

No puede tener como elementos, listas, _tuples_, ni _dictionaries_.

**frozenset():** Es una variable tipo _set_ que no se puede modificar.

In [174]:
# Se define con llaves o con el comando "set()"
set1 = {1,math.pi,"abc"}
print(set1)

set2 = {123,2*math.pi,"abcd"}
print(set2)#Se cambia el orden

set3 = set([123,2*math.pi,"abcd",123,2*math.pi,"abcd"]) #El parámetro de la función es una lista
print(set3)#No se repiten los elementos

set_v = set()
print(set_v)#Conjunto vacío

print(frozenset({2,4,6,8,10}))

{1, 3.141592653589793, 'abc'}
{123, 'abcd', 6.283185307179586}
{123, 'abcd', 6.283185307179586}
set()
frozenset({2, 4, 6, 8, 10})


In [125]:
# Agregar un elemento
set1.add(2)
print(set1)

# Agregar varios elementos
set1.update([4,5,6,7])
print(set1)


{1, 2, 3.141592653589793, 'abc'}
{1, 2, 3.141592653589793, 4, 5, 6, 7, 'abc'}


In [126]:
#Eliminar elementos

set1.discard('abc')
print(set1)

set1.discard('bcd')
print(set1)# No causa error si el elemento no existe en el conjunto

set1.remove(4)
print(set1)

set1.remove('bcd')
print(set1)# Causa error si el elemento no existe en el conjunto


{1, 2, 3.141592653589793, 4, 5, 6, 7}
{1, 2, 3.141592653589793, 4, 5, 6, 7}
{1, 2, 3.141592653589793, 5, 6, 7}


KeyError: 'bcd'

In [128]:
print(set2)
print(set2.pop()) #Se muestra y se elimina un elemento del conjunto
print(set2)

set2.clear() #Se vacía el conjunto
print(set2)

{'abcd', 6.283185307179586}
abcd
{6.283185307179586}
set()


### OPERACIONES DE CONJUNTOS

Permite operaciones como unión, intersección, diferencia, ...

In [138]:
A = {1,2,3,4,5}
B = {5,6,7,8,9,10}

#Unión
print(A | B)
print(A.union(B))
print(B.union(A))

#Intersección
print(A & B)
print(A.intersection(B))
print(B.intersection(A))

#Diferencia
print(A - B)
print(B - A)
print(A.difference(B))
print(B.difference(A))

#Diferencia simétrica: (A-B) U (B-A)
print(A ^ B)
print(A.symmetric_difference(B))
print(B.symmetric_difference(A))

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
{5}
{5}
{5}
{1, 2, 3, 4}
{6, 7, 8, 9, 10}
{1, 2, 3, 4}
{6, 7, 8, 9, 10}
{1, 2, 3, 4, 6, 7, 8, 9, 10}
{1, 2, 3, 4, 6, 7, 8, 9, 10}
{1, 2, 3, 4, 6, 7, 8, 9, 10}


In [139]:
#Conjuntos disjuntos
A.isdisjoint(B) #Arroja 'false' porque los conjuntos no son disjuntos, tienen como elemento común el '5'.

False

In [140]:
#Subconjunto
C = {1,2,3}
C.issubset(A) #¿C es subconjunto de A?

True

In [142]:
#Pertenencia en el conjunto
print(5 in A)
print(5 not in A)


True
False


### DICTIONARY

Es una colección no ordenada de elementos. Se puede definir con llaves o con el comando _dict()_ Cada elemento consta de dos valores _key/value_.

El valor _key_ debe ser único y debe ser de una variable que no se pueda cambiar, por ejemplo _tuple_ o _frozenset_.

El valor _value_ puede ser de cualquier tipo y puede repetirse.

In [199]:
dic1 = dict([(1,'agua'),(2,'luz'),(3,'gas'),(4,'teléfono'),(5,'ocio')])
print(dic1)

dic2 = {
  "marca": "Ford",
  "automático": False,
  "eléctrico": True,
  "año": 1968,
  "colores": ["rojo", "negro", "azul"]
}
print(dic2)


{1: 'agua', 2: 'luz', 3: 'gas', 4: 'teléfono', 5: 'ocio'}
{'marca': 'Ford', 'automático': False, 'eléctrico': True, 'año': 1968, 'colores': ['rojo', 'negro', 'azul']}


In [203]:
#Ver información
print(dic1[2])
print(dic2['colores'])

#Muestra los elementos del diccionario
print(dic1.items())

#Muestra las llaves del diccionario
print(dic1.keys())

#Muestra los valores del diccionario
print(dic1.values())

luz
['rojo', 'negro', 'azul']
dict_items([(1, 'agua'), (2, 'luz'), (3, 'gas'), (4, 'teléfono'), (5, 'ocio')])
dict_keys([1, 2, 3, 4, 5])
dict_values(['agua', 'luz', 'gas', 'teléfono', 'ocio'])


In [189]:
# Cambiar información
dic1[5] = 'renta'
dic2['colores'] = ["rojo", "negro", "azul","blanco"]

print(dic1)
print(dic2)

{1: 'agua', 2: 'luz', 3: 'gas', 4: 'teléfono', 5: 'renta'}
{'marca': 'Ford', 'automático': False, 'eléctrico': True, 'año': 1968, 'colores': ['rojo', 'negro', 'azul', 'blanco']}


In [194]:
# Quitar un elemento
print(dic1.pop(4))
print(dic1)

teléfono
{1: 'agua', 2: 'luz', 3: 'gas', 5: 'ocio'}


In [197]:
# Quitar el último elemento
print(dic2)
print(dic2.popitem())
print(dic2)

{'marca': 'Ford', 'automático': False, 'eléctrico': True}
('eléctrico', True)
{'marca': 'Ford', 'automático': False}


### FUNCIONES QUE SE APLICAN A VARIABLES TIPO _LIST, SET, DICTIONARY,..._

- **all():** Regresa "TRUE" si todos los elementos son "TRUE" o si la variable es vacía.

- **any():** Regresa "TRUE" si algún elemento es "TRUE". Si la variable es vacía, regresa "FALSE".

- **enumerate():** Regresa un objeto enumerado.

- **len():** Regresa el número de elementos de la variable.

- **max():** Regresa el elemento más grande.

- **min():** Regresa el elemento más pequeño.

- **sorted():** Regresa una lista ordenada de los elementos.

- **sum():** Regresa la suma de los elementos.

In [147]:
# Función all()
print(A)
print(all(A))

print(tuple3)
print(all(tuple3))

{1, 2, 3, 4, 5}
True
(True, False, True, False)
False


In [150]:
# Función any()
print(A)
print(tuple3)

print(any(A))
print(any(tuple3))
print(any([0,False]))

{1, 2, 3, 4, 5}
(True, False, True, False)
True
True
False


In [153]:
# Función enumerate()
lista_num = enumerate(lista_1, start = 1)
print(list(lista_num))

[(1, 'abc'), (2, 'def'), (3, 'ghi')]


In [158]:
# Función len()
len(B)

6

In [159]:
# Función max()
max(B)

10

In [160]:
# Función min()
min(B)

5

In [171]:
# Función sorted()
print(lista_2)
print(sorted(lista_2))
print(lista_2)#No cambia la lista

print(sorted(lista_2,reverse=True))#Ordena de mayor a menor

print(lista_5)
print(sorted(lista_5, key=len))#Ordena de acuerdo a la longitud de los elementos

[1, 2, 3, 4, 5, 6, 7, 8, 9, 3]
[1, 2, 3, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 3]
None
[9, 8, 7, 6, 5, 4, 3, 3, 2, 1]
['lista', 'con', 'caracteres']
['con', 'lista', 'caracteres']


In [172]:
# Función sum()
print(A)
sum(A)

{1, 2, 3, 4, 5}


15

### DIFERENCIAS ENTRE _LIST, TUPLE, SET _ Y _DICTIONARY_

|            |                                 List                                |             Tuple            |                    Set                    |                                         Dictionary                                        |
|------------|:-------------------------------------------------------------------:|:----------------------------:|:-----------------------------------------:|:-----------------------------------------------------------------------------------------:|
| Definición |                                  []                                 |              ()              |                     {}                    |                                        {key:value}                                        |
| Ejemplo    |                             l = [1,2,3]                             |         t = (1,2,3,)         |             s = {1,1,2,2,3,3}             |                               d = {1:'Frutas',2:'Verduras'}                               |
| Ordenado   |                                  SI                                 |              SI              |                     NO                    |                                             NO                                            |
| Cambia     |                                  SI                                 |              NO              |                     SI                    |                                     key-No / value-SI                                     |
| Elem. rep. |                                  SI                                 |              SI              |                     NO                    |                                     key-NO / value-SI                                     |
| Acceso     |                             print(l[0])                             |          print(t[0])         |                  print(s)                 |                                            d[1]                                           |
| Uso        | Con datos sin acceso aleatorio. Variable modificada frecuentemente. | Cuando los datos no cambian. | Cuando no se desean elementos duplicados. | Se tiene una asociación lógica en pares. Vista rápida a elementos por medio de una llave. |
|            |                                                                     |                              |                                           |                                                                                           |